### ISSUE TITLE
Missing AWS::EC2::VPCEndpointService and other discrepancies

### ISSUE THREAD

**Issue by andreyk0** [freckle/stratosphere#111]
Hi, guys!
This is probably more of an FYI and a question than an issue report but wanted to mention.

We ran into an issue with `AWS::EC2::VPCEndpointService` being missing in the API, which turned out to be an AWS problem, we have a support ticket open.
Similarly just bumped into another issue where AWS published resource property as an `VPCEndpointType` where's it has to be `VpcEndpointType`.

Both issues are clearly AWS problems, one of them was known to AWS for a while and they already had an internal ticket ... which brings a question of how to deal with that?

For now I'm just "forking" the project and will attempt to "fix" the downloaded AWS JSON by hand but there's got to be a more intelligent way of "patching" the official but incorrect specifications.

Any good suggestions? Is it worth adding some sort of formal `CloudFormationResourceSpecification.json` patching mechanism to this project?

Thanks!

**Comment by jdreaver** [comment]
We can't use `patch` on the raw JSON effectively because the diffs on that are horrendous; stuff gets moved around all the time for no reason.

I actually do have an ad-hoc patching mechanism in the Haskell code. Check out this function https://github.com/frontrowed/stratosphere/blob/34827b93db58495a60896b4cb132353bc0734e5c/gen/src/Gen/Specifications.hs#L44-L94

I haven't touched it in a while so some of the things in that function might be fixed already, but in general I try to add fixes that are idempotent, so if they are fixed by AWS nothing breaks. We could add these fixes there.

**Comment by andreyk0** [comment]
Cool, thanks for the pointers!
I'll hack this for now in our fork so that we can deploy something but I'll come back afterwards and try to do it your way.
This AWS JSON is much messier than I ever imagined, seems to be completely ad-hoc. Tried to pull latest version of it before I make tweaks and there are properties and doc sections missing, they've introduced `Map` type that seems to be synonymous with `Json` etc ... sorry for the rant, trying to wrap my head around it.

**Comment by jdreaver** [comment]
Yeah the JSON is super useful, but it has a ton of warts.

> they've introduced `Map` type that seems to be synonymous with `Json` etc

That actually looks like a bug to me. I just manually edit it back to `Json`.

```diff
@@ -26933,7 +26973,7 @@
         "InstanceAttributes": {
           "Required": true,
           "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicediscovery-instance.html#cfn-servicediscovery-instance-instanceattributes",
+          "PrimitiveType": "Json",
-          "PrimitiveType": "Map",
           "UpdateType": "Mutable"
         },
         "InstanceId": {
```

I should probably talk to AWS support about it :grimacing:

**Comment by andreyk0** [comment]
Please take a look: https://github.com/frontrowed/stratosphere/pull/112
This seems to work for me. I've refrained from updating to the latest JSON spec for now (which has other warts), just focusing on these for now.

Thanks for your help!

**Comment by andreyk0** [comment]
@jdreaver I've updated the code some more. Tried to apply your pattern of "fixing JSON warts in the code" all the way. Downloaded latest spec JSON using your script and with latest code tweaks it generates / compiles.

Please let me know let me know what you think. I'm happy to make more changes if you don't like something. 

I didn't commit the results of codegen but you can see them here: https://github.com/EarnestResearch/stratosphere/tree/codegen

We are trying to build our infra around this library, happy to help you work on it if you are interested.

**Comment by jdreaver** [comment]
Hey @andreyk0 thanks a lot! I'll move discussion over to that PR.

**Comment by jdreaver** [comment]
FYI It looks like VPC Endpoint exists in the spec doc now. See https://github.com/freckle/stratosphere/blob/master/library-gen/Stratosphere/Resources/EC2VPCEndpoint.hs

**Comment by andreyk0** [comment]
Awesome! Thanks for your help!
Updating our stuff to the latest ...

**Comment by andreyk0** [comment]
Oh, sorry, spoke too soon ... `AWS::EC2::VPCEndpointService` is still missing.
It **is** confusing, they have similar names but they **are** different resources:
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpoint.html

Can we re-open this issue or should I create a separate one?

**Comment by andreyk0** [comment]
How do you prefer to handle this?
Should I rebase / clean up my earlier patch against the latest `master` ?

**Comment by jdreaver** [comment]
Has AWS support gotten back to you about the resource spec doc updates?

To be honest, I hesitate to add all of these resources/properties manually outside of the resource spec doc. I don't want to accidentally diverge from what the spec doc dictates when this stuff is eventually added. Is it possible for you to maintain a fork of this project until these resources are added?

**Comment by andreyk0** [comment]
I got the usual "thank you, blah, blah, can't promise, blah, watch our blog" response.
In other words - no idea **when** it'll get actually fixed.

On the other hand, now that we have 
```

**Comment by andreyk0** [comment]
Ok, your recent changes made this workaround easier, thanks!
Indeed I don't have to maintain a full fork anymore, can just add one affected resource to my project and implement `ToResourceProperties`.

If anyone else bumps into this, here it is for reference:
```haskell
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}
{-# LANGUAGE TupleSections     #-}

{- | AWS bug, missing resource, see
     https://github.com/freckle/stratosphere/issues/111

     https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html
-}

module Stratosphere.Resources.EC2VPCEndpointService where

import Stratosphere.ResourceImports


-- | Full data type definition for EC2VPCEndpointService. See
-- 'ec2VPCEndpointService' for a more convenient constructor.
data EC2VPCEndpointService =
  EC2VPCEndpointService
  { _eC2VPCEndpointServiceAcceptanceRequired      :: Maybe (Val Bool)
  , _eC2VPCEndpointServiceNetworkLoadBalancerArns :: ValList Text
  } deriving (Show, Eq)


instance ToResourceProperties EC2VPCEndpointService where
  toResourceProperties EC2VPCEndpointService{..} =
    ResourceProperties
    { resourcePropertiesType = "AWS::EC2::VPCEndpointService"
    , resourcePropertiesProperties =
        hashMapFromList $ catMaybes
          [ fmap (("AcceptanceRequired",) . toJSON . fmap Bool) _eC2VPCEndpointServiceAcceptanceRequired
          , (Just . ("NetworkLoadBalancerArns",) . toJSON) _eC2VPCEndpointServiceNetworkLoadBalancerArns
          ]
    }


-- | Constructor for 'EC2VPCEndpointService' containing required fields as
-- arguments.
ec2VPCEndpointService
  :: ValList Text -- ^ 'ecvpcesNetworkLoadBalancerArns'
  -> EC2VPCEndpointService
ec2VPCEndpointService networkLoadBalancerArnsarg =
  EC2VPCEndpointService
  { _eC2VPCEndpointServiceAcceptanceRequired = Nothing
  , _eC2VPCEndpointServiceNetworkLoadBalancerArns = networkLoadBalancerArnsarg
  }

-- | https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html#cfn-ec2-vpcendpointservice-acceptancerequired
ecvpcesAcceptanceRequired :: Lens' EC2VPCEndpointService (Maybe (Val Bool))
ecvpcesAcceptanceRequired = lens _eC2VPCEndpointServiceAcceptanceRequired (\s a -> s { _eC2VPCEndpointServiceAcceptanceRequired = a })

-- | https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html#cfn-ec2-vpcendpointservice-networkloadbalancerarns
ecvpcesNetworkLoadBalancerArns :: Lens' EC2VPCEndpointService (ValList Text)
ecvpcesNetworkLoadBalancerArns = lens _eC2VPCEndpointServiceNetworkLoadBalancerArns (\s a -> s { _eC2VPCEndpointServiceNetworkLoadBalancerArns = a })

```

**Comment by jdreaver** [comment]
Oh wow I hadn't even thought of the fact that no more big sum type means people can implement their own resources. Cool!

**Comment by PatMyron** [comment]
[`AWS::EC2::VPCEndpointService`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-vpcendpointservice.html) is now in the [CloudFormation Resource Specification](https://d1uauaxba7bl26.cloudfront.net/latest/gzip/CloudFormationResourceSpecification.json)

---

> We can't use patch on the raw JSON effectively because the diffs on that are horrendous; stuff gets moved around all the time for no reason.

Sorting with [jq](https://stedolan.github.io/jq/) reduces diff noise

---

The [CloudFormation Linter](https://github.com/aws-cloudformation/cfn-python-lint/tree/master/src/cfnlint/data/ExtendedSpecs), [CDK](https://github.com/aws/aws-cdk/tree/master/packages/%40aws-cdk/cfnspec/spec-source), and [Troposphere](https://github.com/cloudtools/troposphere/tree/master/troposphere) also patch the Resource Specification
Ideally, each project shouldn't need to maintain their own set of patches

**Comment by andreyk0** [comment]
Yeah, we can close this, confirmed that `VPCEndpointService` is there and generates same output.

@PatMyron in my opinion *ideally* AWS CloudFormation team would take care not to release broken/incomplete specifications and, when they do, quickly react to customer support tickets (which we've immediately raised) about such issues. The very fact that multiple patch versions of their published spec even exist tells you that people tried to get them to do their job and just gave up.

**Comment by jdreaver** [comment]
Yeah I've become increasingly frustrated with this spec document. In fact, I actually totally ignore `WAFv2` resources because almost all of them are malformed

https://github.com/freckle/stratosphere/blob/880c3cae4c2360f71c601f6a88c9e8cdbda9ea7c/gen/src/Main.hs#L27-L35
